import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import AuthProvider from "@/context/authProvider";
import Hearder from "@/components/layout/Hearder";
import Footer from "@/components/layout/Footer";
import { Toaster } from "@/components/ui/toaster";
import { ThemeProvider } from "@/components/layout/ThemeProvider";

const roboto = Roboto({ subsets: ["latin"], weight: ["400", "500", "700"] });

export const metadata: Metadata = {
  title: "Daily Tasks Streak App",
  description: "Generated by Alrehman Ai",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <main className="max-w-7xl mx-auto p-4">
            <AuthProvider>
              <Hearder />
              <Toaster />
              {children}
              <Footer />
            </AuthProvider>
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
